### ISSUE TITLE
Bad behavior when attempting to advance workflow from outside EPNET (without VPN)

### ISSUE THREAD

**Issue by domq** [epfl-si/PhDAssess#30]
What we tested (with Éd) today: click on the Submit (red) button on the very last step of a workflow, while VPN was off, from outside EPFL.

Expected behavior: some kind of error message

Actual behavior: absolutely nothing happens. No green success message, no throbber in the red button, nothing.

**Comment by jdelasoie** [comment]
Should be fixed since 1.12.0, as the form is loaded through a method, and not a subscription anymore.
